### ISSUE TITLE
Canm You Help Me Please!

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [eaglesoftware777/neogeosdk#1]
Hey yall, so i have a problem here, idk where to add xtools and the neogeosdk at in my path directory, also I am running on ubuntu.

**Comment by eaglesoftware777** [comment]
Hello, You should copy them into your linux home directory ~
your home directory in ubuntu is : /home/**your-username**/
The symbol **~** denote the home directory , also $HOME bash variable
At ubuntu terminal you can just use the following commands :
cp -r neogeosdk ~       
cp -r xtools ~

You can also clone directly negeosdk via git to your home directory
cd ~
git clone https://github.com/eaglesoftware777/neogeosdk.git
